name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.3.4-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7411babdd60dca00dcc5cab3c4d5a1229b680ea366f37ae872c643fd2b8cb4ca"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
