name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.4.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a207c5ad94cb6b2bfb0bf38ebd9c48bd2d6ffc5965fc605455c1bb4ada310b"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
