name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.3.4-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b971064061aeff6bba24f367d7c19b21786f506c96f5d66bf7a9715bad8e3f"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
