name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.2.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bbcedbeac84f2e1721af8c3c2159768554ed913debbbddaf20d9dd7ab0d7dfd"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
