name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48746d79e77e0f2baebb385d0135b1787e770c9d963660284d57c21fb1f17a2a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
