name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.3.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c726dfce2a8a7d4b574d45d4065825fe309f453ffedeb342f3ec7bd72687b0ce"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
