name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.3.4-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abc59a91f756ea5c1ce668b91edf7150216f9ef8ed16df63c2aa1b95b7fc3930"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
