name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.3.3-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eafd38dd63f2f0e2afef0fa7ce7b83227b9703d0873b7894a5e42c729bfd8dbb"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
