name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.2.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09826aa49a1da69055865d731b1aff82b2a8c9c2fca4148d476f4df6ee9d9549"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
