name = "Wayfarer - A New Adventure"
author = "TheMysticalBard"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da606fa49d64bbf33ebd0017befcefd3067e33b03e4145ad0680f3dec80c1080"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
datapack-folder = "paxi/datapacks"
