#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 0 ~ 4
Difficulty = 2

["Item settings"]
	#Fire Resistance blocks all hot temperatures
	"Fire Resistance Immunity" = true
	#Ice Resistance blocks all cold temperatures
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see world temperature
	"Require Thermometer" = true

["Misc temperature-related things"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Prevent Sleep When in Danger" = true

["Details about how the player is affected by temperature"]
	#Defines the minimum habitable temperature
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.42857142857142855
	#Defines the maximum habitable temperature
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.619047619047619
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 1.0

["Temperature Effects"]

	["Temperature Effects".Hot]
		#When set to true, the player's view distance will decrease when they are too hot
		"Heatstroke Fog" = true

	["Temperature Effects".Cold]
		#When set to true, some of the player's hearts will freeze when they are too cold, preventing regeneration
		"Freezing Hearts" = true
		#When set to true, the player's attack knockback will be reduced when they are too cold
		"Cold Knockback Reduction" = true
		#When set to true, the player's movement speed will be reduced when they are too cold
		"Cold Slowness" = true
		#When set to true, the player's mining speed will be reduced when they are too cold
		"Cold Mining Fatigue" = true

["Grace Period Details"]
	#Grace period length in ticks (default: 6000)
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period (default: true)
	"Grace Period Enabled" = true

[Hearth]
	#How strong the hearth is (default: 0.5)
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5
	#List of blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "windswept:holly_leaves", "windswept:chestnut_leaves", "thermal:rubberwood_leaves", "byg:araucaria_leaves", "byg:aspen_leaves", "byg:baobab_leaves", "byg:blooming_witch_hazel_leaves", "byg:blue_enchanted_leaves", "byg:blue_spruce_leaves", "byg:brown_birch_leaves", "byg:brown_oak_leaves", "byg:brown_zelkova_leaves", "byg:cika_leaves", "byg:cypress_leaves", "byg:ebony_leaves", "byg:embur_gel_vines", "byg:embur_gel_vines_plant", "byg:ether_leaves", "byg:fir_leaves", "byg:firecracker_leaves", "byg:flowering_baobab_leaves", "byg:flowering_indigo_jacaranda_leaves", "byg:flowering_jacaranda_leaves", "byg:flowering_joshua_leaves", "byg:flowering_nightshade_leaves", "byg:flowering_orchard_leaves", "byg:flowering_palo_verde_leaves", "byg:flowering_skyris_leaves", "byg:green_apple_skyris_leaves", "byg:green_enchanted_leaves", "byg:holly_berry_leaves", "byg:holly_leaves", "byg:imparius_vine", "byg:imparius_vine_plant", "byg:indigo_jacaranda_leaves", "byg:jacaranda_leaves", "byg:joshua_leaves", "byg:lament_leaves", "byg:mahogany_leaves", "byg:maple_leaves", "byg:nightshade_leaves", "byg:orange_birch_leaves", "byg:orange_oak_leaves", "byg:orange_spruce_leaves", "byg:orchard_leaves", "byg:palm_leaves", "byg:palo_verde_leaves", "byg:pine_leaves", "byg:pink_cherry_leaves", "byg:poison_ivy", "byg:rainbow_eucalyptus_leaves", "byg:red_birch_leaves", "byg:red_maple_leaves", "byg:red_oak_leaves", "byg:red_spruce_leaves", "byg:redwood_leaves", "byg:ripe_baobab_leaves", "byg:ripe_joshua_leaves", "byg:ripe_orchard_leaves", "byg:shulkren_vine", "byg:shulkren_vine_plant", "byg:silver_maple_leaves", "byg:skyris_leaves", "byg:skyris_vine", "byg:white_cherry_leaves", "byg:white_mangrove_leaves", "byg:willow_leaves", "byg:witch_hazel_leaves", "byg:withering_oak_leaves", "byg:yellow_birch_leaves", "byg:yellow_spruce_leaves", "byg:zelkova_leaves", "aether:skyroot_leaves", "aether:golden_oak_leaves", "aether:crystal_leaves", "aether:crystal_fruit_leaves", "aether:holiday_leaves", "aether:decorated_holiday_leaves", "deep_aether:roseroot_leaves", "deep_aether:blue_roseroot_leaves", "deep_aether:flowering_roseroot_leaves", "deep_aether:flowering_blue_roseroot_leaves", "deep_aether:yagroot_leaves", "deep_aether:cruderoot_leaves", "deep_aether:conberry_leaves", "deep_aether:sunroot_leaves", "deep_aether:yagroot_roots", "aether_redux:blightwillow_leaves", "aether_redux:glacia_leaves", "aether_redux:gilded_oak_leaves", "aether_redux:chromatic_berry_leaves", "aether_redux:chromatic_leaves", "aether_redux:flowering_fieldsprout_leaves", "aether_redux:blighted_skyroot_leaves", "twilightforest:rainbow_oak_leaves", "twilightforest:twilight_oak_leaves", "twilightforest:canopy_leaves", "twilightforest:mangrove_leaves", "twilightforest:dark_leaves", "twilightforest:time_leaves", "twilightforest:transformation_leaves", "twilightforest:mining_leaves", "twilightforest:sorting_leaves", "twilightforest:thorn_leaves", "twilightforest:beanstalk_leaves", "ars_nouveau:purple_archwood_leaves", "ars_nouveau:blue_archwood_leaves", "ars_nouveau:red_archwood_leaves", "ars_nouveau:green_archwood_leaves", "twilightdelight:ironwood_leaves", "undergarden:smogstem_leaves", "undergarden:wigglewood_leaves", "undergarden:grongle_leaves", "environmental:willow_leaves", "environmental:pink_wisteria_leaves", "environmental:blue_wisteria_leaves", "environmental:purple_wisteria_leaves", "environmental:white_wisteria_leaves", "environmental:cherry_leaves", "upgrade_aquatic:river_leaves", "regions_unexplored:alpha_leaves", "regions_unexplored:apple_oak_leaves", "regions_unexplored:ashen_leaves", "regions_unexplored:bamboo_leaves", "regions_unexplored:baobab_leaves", "regions_unexplored:blackwood_leaves", "regions_unexplored:cobalt_webbing", "regions_unexplored:brimwood_leaves", "regions_unexplored:cypress_leaves", "regions_unexplored:dead_leaves", "regions_unexplored:dead_pine_leaves", "regions_unexplored:eucalyptus_leaves", "regions_unexplored:flowering_leaves", "regions_unexplored:golden_larch_leaves", "regions_unexplored:joshua_leaves", "regions_unexplored:kapok_leaves", "regions_unexplored:larch_leaves", "regions_unexplored:maple_leaves", "regions_unexplored:mauve_leaves", "regions_unexplored:orange_maple_leaves", "regions_unexplored:palm_leaves", "regions_unexplored:pine_leaves", "regions_unexplored:blue_magnolia_leaves", "regions_unexplored:pink_magnolia_leaves", "regions_unexplored:redwood_leaves", "regions_unexplored:red_maple_leaves", "regions_unexplored:magnolia_leaves", "regions_unexplored:silver_birch_leaves", "regions_unexplored:small_oak_leaves", "regions_unexplored:socotra_leaves", "regions_unexplored:enchanted_birch_leaves", "regions_unexplored:white_magnolia_leaves", "regions_unexplored:willow_leaves", "atmospheric:rosewood_leaves", "atmospheric:morado_leaves", "atmospheric:flowering_morado_leaves", "atmospheric:yucca_leaves", "atmospheric:kousa_leaves", "atmospheric:aspen_leaves", "atmospheric:grimwood_leaves", "quark:blue_blossom_leaves", "quark:lavender_blossom_leaves", "quark:orange_blossom_leaves", "quark:pink_blossom_leaves", "quark:yellow_blossom_leaves", "quark:red_blossom_leaves", "quark:ancient_leaves", "ars_elemental:yellow_archwood_leaves"]
	#List of blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

